# Generated by Django 5.0.3 on 2024-06-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rangi', models.CharField(max_length=200)),
                ('tami', models.CharField(max_length=200)),
                ('ibsn', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
